"""CLDR's month and weekday names: package data, written by one script.

``src/sluicer/calendar_names.json`` is generated by ``scripts/cldr_calendar.py``
from the pinned CLDR release. The suite opens no socket, so it holds the file
to the script in the two ways that need none: the committed file is exactly
what the script writes for the names it holds, and the script reads a CLDR
release as its docstring says, on a small one built here. That the names are
the pinned release's own is checked where the network is, by
``scripts/cldr_calendar.py --check`` in CI.
"""

from __future__ import annotations

import importlib.resources
import importlib.util
import io
import json
import tarfile
from pathlib import Path

from sluicer.calendar_names import MONTHS, WEEKDAYS

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "src" / "sluicer" / "calendar_names.json"


def _script():
    path = ROOT / "scripts" / "cldr_calendar.py"
    spec = importlib.util.spec_from_file_location("cldr_calendar", path)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _tarball(files: dict[str, object]) -> tarfile.TarFile:
    buffer = io.BytesIO()
    with tarfile.open(fileobj=buffer, mode="w:gz") as tar:
        for name, content in files.items():
            data = json.dumps(content, ensure_ascii=False).encode("utf-8")
            info = tarfile.TarInfo(f"package/{name}")
            info.size = len(data)
            tar.addfile(info, io.BytesIO(data))
    buffer.seek(0)
    return tarfile.open(fileobj=buffer, mode="r:gz")


def _calendar(locale: str, months: dict[str, list[str]], days: list[str]) -> dict:
    """A ``ca-gregorian.json`` whose four month forms are ``months``'s, keyed
    by width, and whose weekdays are ``days`` in every form."""

    def numbered(names: list[str]) -> dict[str, str]:
        return {str(number): name for number, name in enumerate(names, start=1)}

    def forms(of: dict[str, list[str]]) -> dict:
        return {
            context: {width: numbered(names) for width, names in of.items()}
            for context in ("format", "stand-alone")
        }

    week = {"wide": days, "abbreviated": days}
    gregorian = {"months": forms(months), "days": forms(week)}
    return {"main": {locale: {"dates": {"calendars": {"gregorian": gregorian}}}}}


def test_the_names_are_package_data_under_their_own_licence():
    shipped = importlib.resources.files("sluicer") / "calendar_names.json"
    data = json.loads(shipped.read_text(encoding="utf-8"))
    assert data["licence"] == "Unicode-3.0"
    assert data["cldr"] == _script().RELEASE
    # The module that loads them is ours, and holds no name of CLDR's.
    loader = (ROOT / "src" / "sluicer" / "calendar_names.py").read_text("utf-8")
    assert len(loader.splitlines()) < 60
    assert "abendua" not in loader


def test_the_committed_file_is_what_the_script_writes_for_its_names():
    """A hand edit, a reordering or a reformatting of the file fails here."""
    committed = DATA.read_text(encoding="utf-8")
    data = json.loads(committed)
    rewritten = _script().rendered(
        data["months"], data["weekdays"], data["locales"], data["left_out"]
    )
    assert rewritten == committed


def test_the_module_gives_every_name_the_file_holds():
    data = json.loads(DATA.read_text(encoding="utf-8"))
    assert data["months"] == MONTHS
    assert frozenset(data["weekdays"]) == WEEKDAYS
    assert len(data["weekdays"]) == len(WEEKDAYS)
    assert all(isinstance(n, int) and 1 <= n <= 12 for n in MONTHS.values())
    assert isinstance(WEEKDAYS, frozenset)
    assert MONTHS["mai"] == 5 and "montag" in WEEKDAYS


def test_the_script_reads_a_cldr_release_as_it_says():
    script = _script()
    core = _tarball(
        {
            "coverageLevels.json": {
                "effectiveCoverageLevels": {
                    "ca": "modern",
                    "hr": "modern",
                    "pl": "modern",
                    "ru": "modern",
                    "xx": "basic",
                    "zz": "modern",
                }
            }
        }
    )
    twelve = [f"m{letter}" for letter in "abcdefghijkl"]
    polish = [*twelve[:10], "listopad", "gru"]
    croatian = [*twelve[:9], "listopad", "stu", "pro"]
    dates = _tarball(
        {
            "main/ca/ca-gregorian.json": _calendar(
                "ca",
                {"wide": ["de gener", *twelve[1:]], "abbreviated": twelve},
                ["dilluns", "dimarts"],
            ),
            "main/pl/ca-gregorian.json": _calendar(
                "pl", {"wide": polish, "abbreviated": polish}, ["poniedziałek"]
            ),
            "main/hr/ca-gregorian.json": _calendar(
                "hr", {"wide": croatian, "abbreviated": croatian}, ["ponedjeljak"]
            ),
            "main/ru/ca-gregorian.json": _calendar(
                "ru",
                {"wide": [*twelve[:4], "Мая", *twelve[5:]], "abbreviated": twelve},
                ["Пн.", "mc"],
            ),
            "main/xx/ca-gregorian.json": _calendar(
                "xx", {"wide": twelve, "abbreviated": twelve}, ["basicday"]
            ),
            "main/zz/ca-gregorian.json": _calendar(
                "zz",
                {"wide": [f"{n}月" for n in range(1, 13)], "abbreviated": twelve},
                ["木"],
            ),
        }
    )
    months, weekdays, locales, left_out = script.names(core, dates)
    # Every modern locale with a Gregorian calendar, the basic one not.
    assert locales == 5
    # Catalan's preposition taken off, Russian casefolded, the digits out.
    assert months["gener"] == 1 and months["мая"] == 5
    assert not any("月" in name for name in months)
    # "listopad" is November in Polish and October in Croatian: out.
    assert "listopad" not in months and left_out == ["listopad"]
    assert months["mj"] == 10 and months["gru"] == 12 and months["pro"] == 12
    # A weekday that is also a month is left to the months: "mc" is March.
    assert weekdays == sorted(
        {"dilluns", "dimarts", "poniedziałek", "ponedjeljak", "пн", "木"}
    )
    text = script.rendered(months, weekdays, locales, left_out)
    assert json.loads(text)["months"] == months
    assert text == script.rendered(
        dict(reversed(months.items())), weekdays, locales, left_out
    )
