# SPDX-License-Identifier: Unicode-3.0
# Month and weekday names from the Unicode Common Locale Data Repository
# (CLDR), release 48.2.0, published by Unicode, Inc. under the Unicode
# License v3. This file, unlike most of sluicer, is distributed under that
# licence: see LICENSES/Unicode-3.0.txt. Regenerate it with
# scripts/cldr_calendar.py; do not edit it by hand.
# ruff: noqa: RUF001 -- names in their own scripts, Cyrillic and Greek too.
"""Month and weekday names in every language CLDR covers at its modern level.

430 locales, CLDR 48.2.0: each month's wide and abbreviated
names, in their formatting and stand-alone forms, casefolded, without a
trailing full stop. Names holding a digit are not here -- Chinese,
Japanese and Korean write months as numbers -- nor the names that mean
two months in two locales: lip, lis, listopad, listopada, srp.
"""

MONTHS: dict[str, int] = {
    "abe": 12,
    "abendua": 12,
    "abr": 4,
    "abriil": 4,
    "abril": 4,
    "abu": 8,
    "abuztua": 8,
    "afi": 4,
    "afirilu": 4,
    "ag": 8,
    "aga": 8,
    "agasti": 8,
    "ago": 8,
    "agost": 8,
    "agosti": 8,
    "agosto": 8,
    "agt": 8,
    "agu": 8,
    "agusta": 8,
    "agustus": 8,
    "ahinime": 10,
    "aib": 4,
    "aibreán": 4,
    "am faoilleach": 1,
    "am màrt": 3,
    "an cèitean": 5,
    "an dàmhair": 10,
    "an dùbhlachd": 12,
    "an gearran": 2,
    "an giblean": 4,
    "an lùnastal": 8,
    "an t-iuchar": 7,
    "an t-samhain": 11,
    "an t-sultain": 9,
    "an t-ògmhios": 6,
    "août": 8,
    "api": 4,
    "apirila": 4,
    "apr": 4,
    "aprel": 4,
    "april": 4,
    "aprile": 4,
    "aprili": 4,
    "aprilie": 4,
    "aprill": 4,
    "apryl": 4,
    "apryla": 4,
    "apríl": 4,
    "apríla": 4,
    "aprīlis": 4,
    "ara": 12,
    "aralık": 12,
    "aug": 8,
    "august": 8,
    "augusta": 8,
    "augusti": 8,
    "augusts": 8,
    "augustus": 8,
    "augusztus": 8,
    "avg": 8,
    "avgust": 8,
    "avq": 8,
    "avqust": 8,
    "avr": 4,
    "avrigl": 4,
    "avril": 4,
    "avust": 8,
    "awg": 8,
    "awgust": 8,
    "awgusta": 8,
    "awst": 8,
    "ayɛwohomumu": 6,
    "aza": 11,
    "azaroa": 11,
    "ağu": 8,
    "ağustos": 8,
    "bal": 4,
    "balandis": 4,
    "balandžio": 4,
    "beal": 5,
    "bealtaine": 5,
    "birž": 6,
    "birželio": 6,
    "birželis": 6,
    "bře": 3,
    "březen": 3,
    "března": 3,
    "chw": 2,
    "chwef": 2,
    "chwefror": 2,
    "cze": 6,
    "czerwca": 6,
    "czerwiec": 6,
    "cèit": 5,
    "da december": 12,
    "da fanadur": 7,
    "da favrer": 2,
    "da mars": 3,
    "da matg": 5,
    "da november": 11,
    "da schaner": 1,
    "da settember": 9,
    "da zercladur": 6,
    "dec": 12,
    "decembar": 12,
    "december": 12,
    "decembra": 12,
    "decembrie": 12,
    "decembris": 12,
    "decembro": 12,
    "deireadh fómhair": 10,
    "dek": 12,
    "dekabr": 12,
    "des": 12,
    "desemba": 12,
    "desember": 12,
    "desembre": 12,
    "dets": 12,
    "detsember": 12,
    "dez": 12,
    "dezember": 12,
    "dezembro": 12,
    "dfómh": 10,
    "dhen chèitean": 5,
    "dhen dàmhair": 10,
    "dhen dùbhlachd": 12,
    "dhen fhaoilleach": 1,
    "dhen ghearran": 2,
    "dhen ghiblean": 4,
    "dhen iuchar": 7,
    "dhen lùnastal": 8,
    "dhen mhàrt": 3,
    "dhen t-samhain": 11,
    "dhen t-sultain": 9,
    "dhen ògmhios": 6,
    "dhj": 12,
    "dhjetor": 12,
    "dic": 12,
    "dicembre": 12,
    "diciembre": 12,
    "dis": 12,
    "disamba": 12,
    "diseembar": 12,
    "disemba": 12,
    "disember": 12,
    "disyembre": 12,
    "disẹ́mba": 12,
    "dub": 4,
    "duben": 4,
    "dubna": 4,
    "dàmh": 10,
    "déc": 12,
    "décembre": 12,
    "dùbh": 12,
    "ean": 1,
    "eanáir": 1,
    "ebr": 4,
    "ebrill": 4,
    "eka": 6,
    "ekaina": 6,
    "eki": 10,
    "ekim": 10,
    "elo": 8,
    "elokuu": 8,
    "elokuuta": 8,
    "ene": 1,
    "enero": 1,
    "eph": 4,
    "ephreli": 4,
    "epr": 4,
    "epreel": 4,
    "eyl": 9,
    "eylül": 9,
    "fab": 2,
    "faburairu": 2,
    "fan": 7,
    "fanadur": 7,
    "faoi": 1,
    "favr": 2,
    "favrer": 2,
    "feabh": 2,
    "feabhra": 2,
    "feb": 2,
    "febbraio": 2,
    "febr": 2,
    "febraayo": 2,
    "febreiro": 2,
    "febrer": 2,
    "febrero": 2,
    "februar": 2,
    "februara": 2,
    "februari": 2,
    "februarie": 2,
    "february": 2,
    "februwari": 2,
    "február": 2,
    "februára": 2,
    "februāris": 2,
    "febrúar": 2,
    "febrụwarị": 2,
    "fev": 2,
    "fevereiro": 2,
    "fevral": 2,
    "few": 2,
    "fewral": 2,
    "fév": 2,
    "févr": 2,
    "février": 2,
    "fẹ́b": 2,
    "fẹ́búári": 2,
    "gearr": 2,
    "geg": 5,
    "gegužė": 5,
    "gegužės": 5,
    "gen": 1,
    "gener": 1,
    "gennaio": 1,
    "gibl": 4,
    "giu": 6,
    "giugno": 6,
    "gor": 7,
    "gorff": 7,
    "gorffennaf": 7,
    "gru": 12,
    "grudnia": 12,
    "grudzień": 12,
    "gruod": 12,
    "gruodis": 12,
    "gruodžio": 12,
    "gush": 8,
    "gusht": 8,
    "haz": 6,
    "haziran": 6,
    "heinä": 7,
    "heinäkuu": 7,
    "heinäkuuta": 7,
    "helmi": 2,
    "helmikuu": 2,
    "helmikuuta": 2,
    "huhti": 4,
    "huhtikuu": 4,
    "huhtikuuta": 4,
    "hul": 7,
    "hulyo": 7,
    "hun": 6,
    "hunyo": 6,
    "hyd": 10,
    "hydref": 10,
    "ian": 1,
    "ianuarie": 1,
    "ion": 1,
    "ionawr": 1,
    "ira": 9,
    "iraila": 9,
    "iuch": 7,
    "iul": 7,
    "iulie": 7,
    "iun": 6,
    "iunie": 6,
    "iyl": 7,
    "iyn": 6,
    "iyul": 7,
    "iyun": 6,
    "iúil": 7,
    "iýul": 7,
    "iýun": 6,
    "jaan": 1,
    "jaanuar": 1,
    "jan": 1,
    "janaayo": 1,
    "janairu": 1,
    "janar": 1,
    "janeiro": 1,
    "jannaayo": 1,
    "januar": 1,
    "januara": 1,
    "januari": 1,
    "januarie": 1,
    "january": 1,
    "januwari": 1,
    "január": 1,
    "januára": 1,
    "janv": 1,
    "janvier": 1,
    "janvāris": 1,
    "janúar": 1,
    "jen": 1,
    "jenụwarị": 1,
    "joulu": 12,
    "joulukuu": 12,
    "joulukuuta": 12,
    "jui": 6,
    "juil": 7,
    "juill": 7,
    "juillet": 7,
    "juin": 6,
    "jul": 7,
    "julai": 7,
    "julayi": 7,
    "julaị": 7,
    "julho": 7,
    "juli": 7,
    "julie": 7,
    "julij": 7,
    "julija": 7,
    "julio": 7,
    "juliol": 7,
    "july": 7,
    "jun": 6,
    "june": 6,
    "junho": 6,
    "juni": 6,
    "junie": 6,
    "junij": 6,
    "junija": 6,
    "junio": 6,
    "juny": 6,
    "juu": 6,
    "juuli": 7,
    "juun": 6,
    "juuni": 6,
    "jän": 1,
    "jänner": 1,
    "jén": 1,
    "jénúári": 1,
    "júl": 7,
    "júla": 7,
    "július": 7,
    "júlí": 7,
    "jún": 6,
    "júna": 6,
    "június": 6,
    "júní": 6,
    "jūl": 7,
    "jūlijs": 7,
    "jūn": 6,
    "jūnijs": 6,
    "kas": 11,
    "kasım": 11,
    "kesä": 6,
    "kesäkuu": 6,
    "kesäkuuta": 6,
    "kol": 8,
    "kolovoz": 8,
    "kolovoza": 8,
    "korr": 7,
    "korrik": 7,
    "kov": 3,
    "kovas": 3,
    "kovo": 3,
    "kutawonsa": 7,
    "kvě": 5,
    "květen": 5,
    "května": 5,
    "kwi": 4,
    "kwiecień": 4,
    "kwietnia": 4,
    "kɔtɔnimma": 5,
    "lapkr": 11,
    "lapkritis": 11,
    "lapkričio": 11,
    "led": 1,
    "leden": 1,
    "ledna": 1,
    "liep": 7,
    "liepa": 7,
    "liepos": 7,
    "lipanj": 6,
    "lipca": 7,
    "lipiec": 7,
    "lipnja": 6,
    "listopadu": 11,
    "loka": 10,
    "lokakuu": 10,
    "lokakuuta": 10,
    "lug": 7,
    "luglio": 7,
    "lul": 7,
    "lut": 2,
    "lutego": 2,
    "luty": 2,
    "luulyo": 7,
    "lùna": 8,
    "lún": 8,
    "lúnasa": 8,
    "maa": 3,
    "maachị": 3,
    "maalis": 3,
    "maaliskuu": 3,
    "maaliskuuta": 3,
    "maarso": 3,
    "maart": 3,
    "maayo": 5,
    "mac": 3,
    "mach": 3,
    "machi": 3,
    "mag": 5,
    "maggio": 5,
    "mai": 5,
    "maiatza": 5,
    "maig": 5,
    "maijs": 5,
    "maio": 5,
    "maj": 5,
    "maja": 5,
    "mar": 3,
    "marca": 3,
    "march": 3,
    "marec": 3,
    "maret": 3,
    "maris": 3,
    "marras": 11,
    "marraskuu": 11,
    "marraskuuta": 11,
    "mars": 3,
    "marso": 3,
    "mart": 3,
    "martie": 3,
    "marts": 3,
    "martxoa": 3,
    "marzec": 3,
    "marzo": 3,
    "març": 3,
    "março": 3,
    "mas": 3,
    "mashi": 3,
    "matg": 5,
    "maw": 3,
    "mawrth": 3,
    "may": 5,
    "mayo": 5,
    "mayu": 5,
    "mayıs": 5,
    "maí": 5,
    "maý": 5,
    "medi": 9,
    "mee": 5,
    "meh": 6,
    "mehefin": 6,
    "mei": 5,
    "meith": 6,
    "meitheamh": 6,
    "mej": 5,
    "meja": 5,
    "meje": 5,
    "mey": 5,
    "meyi": 5,
    "meán fómhair": 9,
    "mfómh": 9,
    "mrt": 3,
    "màrt": 3,
    "máj": 5,
    "mája": 5,
    "május": 5,
    "márc": 3,
    "március": 3,
    "márta": 3,
    "mär": 3,
    "märts": 3,
    "märz": 3,
    "měr": 3,
    "měrc": 3,
    "měrca": 3,
    "nis": 4,
    "nisan": 4,
    "nob": 11,
    "nobyembre": 11,
    "nof": 11,
    "noiembrie": 11,
    "noll": 12,
    "nollaig": 12,
    "noofeembar": 11,
    "nov": 11,
    "novemba": 11,
    "novembar": 11,
    "november": 11,
    "novembra": 11,
    "novembre": 11,
    "novembris": 11,
    "novembro": 11,
    "noviembre": 11,
    "now": 11,
    "nowember": 11,
    "nowembra": 11,
    "noy": 11,
    "noyabr": 11,
    "noý": 11,
    "noýabr": 11,
    "nuw": 11,
    "nuwamba": 11,
    "nën": 11,
    "nëntor": 11,
    "nóv": 11,
    "nóvember": 11,
    "nọv": 11,
    "nọvẹ́mba": 11,
    "obubuo": 11,
    "oca": 1,
    "ocak": 1,
    "oct": 10,
    "october": 10,
    "octobre": 10,
    "octombrie": 10,
    "octubre": 10,
    "oforisuo": 4,
    "ogo": 8,
    "ogos": 8,
    "ogosto": 8,
    "ogs": 8,
    "okt": 10,
    "oktabr": 10,
    "okthoba": 10,
    "oktoba": 10,
    "oktobar": 10,
    "oktober": 10,
    "oktobra": 10,
    "oktobris": 10,
    "oktoobar": 10,
    "oktoober": 10,
    "oktubre": 10,
    "oktyabr": 10,
    "október": 10,
    "októbra": 10,
    "oktýabr": 10,
    "oshù agɛmɔ": 7,
    "oshù bélú": 11,
    "oshù owewe": 9,
    "oshù shɛ́rɛ́": 1,
    "oshù èrèlè": 2,
    "oshù ìgbé": 4,
    "oshù ògún": 8,
    "oshù òkúdu": 6,
    "oshù ɔ̀pɛ̀": 12,
    "oshù ɔ̀wàrà": 10,
    "oshù ɛrɛ̀nà": 3,
    "oshù ɛ̀bibi": 5,
    "ots": 2,
    "otsaila": 2,
    "ott": 10,
    "ottobre": 10,
    "out": 10,
    "outubro": 10,
    "ožu": 3,
    "ožujak": 3,
    "ožujka": 3,
    "oṣù agẹmọ": 7,
    "oṣù bélú": 11,
    "oṣù owewe": 9,
    "oṣù èrèlè": 2,
    "oṣù ìgbé": 4,
    "oṣù ògún": 8,
    "oṣù òkúdu": 6,
    "oṣù ṣẹ́rẹ́": 1,
    "oṣù ẹrẹ̀nà": 3,
    "oṣù ẹ̀bibi": 5,
    "oṣù ọ̀pẹ̀": 12,
    "oṣù ọ̀wàrà": 10,
    "paź": 10,
    "październik": 10,
    "października": 10,
    "peb": 2,
    "pebrero": 2,
    "pri": 4,
    "prill": 4,
    "pro": 12,
    "prosinac": 12,
    "prosinca": 12,
    "prosince": 12,
    "prosinec": 12,
    "qer": 6,
    "qershor": 6,
    "rhag": 12,
    "rhagfyr": 12,
    "rugp": 8,
    "rugpjūtis": 8,
    "rugpjūčio": 8,
    "rugs": 9,
    "rugsėjis": 9,
    "rugsėjo": 9,
    "ruj": 9,
    "rujan": 9,
    "rujna": 9,
    "samh": 11,
    "samhain": 11,
    "sat": 9,
    "satumba": 9,
    "saus": 1,
    "sausio": 1,
    "sausis": 1,
    "schan": 1,
    "schaner": 1,
    "seb": 9,
    "sebteembar": 9,
    "sebtembar": 9,
    "sen": 9,
    "sentabr": 9,
    "sentyabr": 9,
    "sentýabr": 9,
    "sep": 9,
    "sept": 9,
    "septemba": 9,
    "septembar": 9,
    "september": 9,
    "septembra": 9,
    "septembre": 9,
    "septembrie": 9,
    "septembris": 9,
    "septhemba": 9,
    "septiembre": 9,
    "set": 9,
    "setembre": 9,
    "setembro": 9,
    "setiembre": 9,
    "sett": 9,
    "settember": 9,
    "settembre": 9,
    "setyembre": 9,
    "shk": 2,
    "shkurt": 2,
    "sht": 9,
    "shtator": 9,
    "sie": 8,
    "sierpień": 8,
    "sierpnia": 8,
    "sij": 1,
    "siječanj": 1,
    "siječnja": 1,
    "spal": 10,
    "spalio": 10,
    "spalis": 10,
    "srpanj": 7,
    "srpen": 8,
    "srpna": 8,
    "srpnja": 7,
    "stu": 11,
    "studeni": 11,
    "studenoga": 11,
    "sty": 1,
    "styczeń": 1,
    "stycznia": 1,
    "sult": 9,
    "svi": 5,
    "svibanj": 5,
    "svibnja": 5,
    "syys": 9,
    "syyskuu": 9,
    "syyskuuta": 9,
    "szept": 9,
    "szeptember": 9,
    "sẹp": 9,
    "sẹptẹ́mba": 9,
    "tach": 11,
    "tachwedd": 11,
    "tammi": 1,
    "tammikuu": 1,
    "tammikuuta": 1,
    "tem": 7,
    "temmuz": 7,
    "tet": 10,
    "tetor": 10,
    "touko": 5,
    "toukokuu": 5,
    "toukokuuta": 5,
    "tra": 4,
    "travanj": 4,
    "travnja": 4,
    "urr": 10,
    "urria": 10,
    "urt": 1,
    "urtarrila": 1,
    "uzt": 7,
    "uztaila": 7,
    "vas": 2,
    "vasario": 2,
    "vasaris": 2,
    "veebr": 2,
    "veebruar": 2,
    "velj": 2,
    "veljača": 2,
    "veljače": 2,
    "wrz": 9,
    "wrzesień": 9,
    "września": 9,
    "xan": 1,
    "xaneiro": 1,
    "xul": 7,
    "xullo": 7,
    "xuño": 6,
    "yan": 1,
    "yanvar": 1,
    "yul": 7,
    "yuli": 7,
    "yun": 6,
    "yuni": 6,
    "zercl": 6,
    "zercladur": 6,
    "zář": 9,
    "září": 9,
    "ágú": 8,
    "ágúst": 8,
    "ápr": 4,
    "április": 4,
    "épr": 4,
    "éprel": 4,
    "ògmh": 6,
    "úno": 2,
    "únor": 2,
    "února": 2,
    "ýan": 1,
    "ýanwar": 1,
    "červen": 6,
    "července": 7,
    "červenec": 7,
    "června": 6,
    "čvc": 7,
    "čvn": 6,
    "říj": 10,
    "říjen": 10,
    "října": 10,
    "şub": 2,
    "şubat": 2,
    "ɔbɛnem": 3,
    "ɔgyefoɔ": 2,
    "ɔpɛnimma": 12,
    "ɔpɛpɔn": 1,
    "ɔsanaa": 8,
    "ɛbɔ": 9,
    "απρ": 4,
    "απρίλιοσ": 4,
    "απριλίου": 4,
    "αὔγουστοσ": 8,
    "αὐγ": 8,
    "αὐγούστου": 8,
    "αυγ": 8,
    "αυγούστου": 8,
    "αύγ": 8,
    "αύγουστοσ": 8,
    "δεκ": 12,
    "δεκέμβριοσ": 12,
    "δεκεμβρίου": 12,
    "ιαν": 1,
    "ιανουάριοσ": 1,
    "ιανουαρίου": 1,
    "ιουλ": 7,
    "ιουλίου": 7,
    "ιουν": 6,
    "ιουνίου": 6,
    "ιούλ": 7,
    "ιούλιοσ": 7,
    "ιούν": 6,
    "ιούνιοσ": 6,
    "μάι": 5,
    "μάιοσ": 5,
    "μάρ": 3,
    "μάρτιοσ": 3,
    "μαΐ": 5,
    "μαΐου": 5,
    "μαρ": 3,
    "μαρτίου": 3,
    "νοέ": 11,
    "νοέμβριοσ": 11,
    "νοε": 11,
    "νοεμβρίου": 11,
    "οκτ": 10,
    "οκτωβρίου": 10,
    "οκτώβριοσ": 10,
    "σεπ": 9,
    "σεπτέμβριοσ": 9,
    "σεπτεμβρίου": 9,
    "φεβ": 2,
    "φεβρουάριοσ": 2,
    "φεβρουαρίου": 2,
    "авг": 8,
    "август": 8,
    "августа": 8,
    "авӑн": 9,
    "ака": 4,
    "апр": 4,
    "апрель": 4,
    "апреля": 4,
    "април": 4,
    "аравдугаар сар": 10,
    "арван нэгдүгээр сар": 11,
    "арван хоёрдугаар сар": 12,
    "ақп": 2,
    "ақпан": 2,
    "бер": 3,
    "березень": 3,
    "березня": 3,
    "вер": 9,
    "верасень": 9,
    "верасня": 9,
    "вересень": 9,
    "вересня": 9,
    "груд": 12,
    "грудень": 12,
    "грудня": 12,
    "гуравдугаар сар": 3,
    "дек": 12,
    "декабрь": 12,
    "декабря": 12,
    "декември": 12,
    "дец": 12,
    "децембар": 12,
    "долоодугаар сар": 7,
    "дөрөвдүгээр сар": 4,
    "есдүгээр сар": 9,
    "жел": 12,
    "желтоқсан": 12,
    "жні": 8,
    "жнівень": 8,
    "жніўня": 8,
    "жовт": 10,
    "жовтень": 10,
    "жовтня": 10,
    "зургаадугаар сар": 6,
    "июл": 7,
    "июль": 7,
    "июля": 7,
    "июн": 6,
    "июнь": 6,
    "июня": 6,
    "кас": 10,
    "кастрычнік": 10,
    "кастрычніка": 10,
    "квіт": 4,
    "квітень": 4,
    "квітня": 4,
    "кра": 4,
    "красавік": 4,
    "красавіка": 4,
    "кӑр": 1,
    "кӑрлач": 1,
    "лип": 7,
    "липень": 7,
    "липня": 7,
    "лист": 11,
    "листопад": 11,
    "листопада": 11,
    "лют": 2,
    "лютага": 2,
    "лютий": 2,
    "лютого": 2,
    "люты": 2,
    "ліп": 7,
    "ліпень": 7,
    "ліпеня": 7,
    "ліс": 11,
    "лістапад": 11,
    "лістапада": 11,
    "май": 5,
    "мам": 5,
    "мамыр": 5,
    "мар": 3,
    "март": 3,
    "марта": 3,
    "мау": 6,
    "маусым": 6,
    "мая": 5,
    "мај": 5,
    "наймдугаар сар": 8,
    "нар": 2,
    "нарӑс": 2,
    "нау": 3,
    "наурыз": 3,
    "нов": 11,
    "новембар": 11,
    "ное": 11,
    "ноември": 11,
    "ноя": 11,
    "нояб": 11,
    "ноябрь": 11,
    "ноября": 11,
    "нэгдүгээр сар": 1,
    "окт": 10,
    "октобар": 10,
    "октомври": 10,
    "октябрь": 10,
    "октября": 10,
    "пуш": 3,
    "раш": 12,
    "раштав": 12,
    "сак": 3,
    "сакавік": 3,
    "сакавіка": 3,
    "сен": 9,
    "сент": 9,
    "сентябрь": 9,
    "сентября": 9,
    "сеп": 9,
    "септ": 9,
    "септембар": 9,
    "септември": 9,
    "серп": 8,
    "серпень": 8,
    "серпня": 8,
    "сне": 12,
    "снежань": 12,
    "снежня": 12,
    "сту": 1,
    "студзень": 1,
    "студзеня": 1,
    "січ": 1,
    "січень": 1,
    "січня": 1,
    "сәу": 4,
    "сәуір": 4,
    "тавдугаар сар": 5,
    "там": 8,
    "тамыз": 8,
    "трав": 5,
    "травень": 5,
    "травня": 5,
    "утӑ": 7,
    "феб": 2,
    "фебруар": 2,
    "фев": 2,
    "февр": 2,
    "февраль": 2,
    "февраля": 2,
    "февруари": 2,
    "хоёрдугаар сар": 2,
    "черв": 6,
    "червень": 6,
    "червня": 6,
    "чэр": 6,
    "чэрвень": 6,
    "чэрвеня": 6,
    "чӳк": 11,
    "шіл": 7,
    "шілде": 7,
    "юли": 7,
    "юни": 6,
    "юпа": 10,
    "янв": 1,
    "январь": 1,
    "января": 1,
    "яну": 1,
    "януари": 1,
    "јан": 1,
    "јануар": 1,
    "јануари": 1,
    "јул": 7,
    "јули": 7,
    "јун": 6,
    "јуни": 6,
    "ғин": 1,
    "ғинуар": 1,
    "қаз": 10,
    "қазан": 10,
    "қар": 11,
    "қараша": 11,
    "қаң": 1,
    "қаңтар": 1,
    "қыр": 9,
    "қыркүйек": 9,
    "ҫу": 5,
    "ҫур": 8,
    "ҫурла": 8,
    "ҫӗрт": 6,
    "ҫӗртме": 6,
    "ապր": 4,
    "ապրիլ": 4,
    "ապրիլի": 4,
    "դեկ": 12,
    "դեկտեմբեր": 12,
    "դեկտեմբերի": 12,
    "հլս": 7,
    "հնս": 6,
    "հնվ": 1,
    "հոկ": 10,
    "հոկտեմբեր": 10,
    "հոկտեմբերի": 10,
    "հուլիս": 7,
    "հուլիսի": 7,
    "հունիս": 6,
    "հունիսի": 6,
    "հունվար": 1,
    "հունվարի": 1,
    "մայիս": 5,
    "մայիսի": 5,
    "մարտ": 3,
    "մարտի": 3,
    "մյս": 5,
    "մրտ": 3,
    "նոյ": 11,
    "նոյեմբեր": 11,
    "նոյեմբերի": 11,
    "սեպ": 9,
    "սեպտեմբեր": 9,
    "սեպտեմբերի": 9,
    "փետրվար": 2,
    "փետրվարի": 2,
    "փտվ": 2,
    "օգոստոս": 8,
    "օգոստոսի": 8,
    "օգս": 8,
    "אוגוסט": 8,
    "אוג׳": 8,
    "אוקטובר": 10,
    "אוק׳": 10,
    "אפריל": 4,
    "אפר׳": 4,
    "דצמבר": 12,
    "דצמ׳": 12,
    "יולי": 7,
    "יוני": 6,
    "ינואר": 1,
    "ינו׳": 1,
    "מאי": 5,
    "מרץ": 3,
    "נובמבר": 11,
    "נוב׳": 11,
    "ספטמבר": 9,
    "ספט׳": 9,
    "פברואר": 2,
    "פבר׳": 2,
    "ءساۋىر": 4,
    "آب": 8,
    "آذار": 3,
    "آوریل": 4,
    "آڪٽوبر": 10,
    "آگسٽ": 8,
    "أبريل": 4,
    "أغسطس": 8,
    "أغشت": 8,
    "أفريل": 4,
    "أكتوبر": 10,
    "أوت": 8,
    "أيار": 5,
    "أيلول": 9,
    "إبريل": 4,
    "اقپان": 2,
    "اوت": 8,
    "اپريل": 4,
    "اپریل": 4,
    "اکتبر": 10,
    "اکتوبر": 10,
    "اګست": 8,
    "اگست": 8,
    "تامىز": 8,
    "تشرين الأول": 10,
    "تشرين الثاني": 11,
    "تشرين الأول": 10,
    "تموز": 7,
    "جانفي": 1,
    "جنو": 1,
    "جنوري": 1,
    "جنوری": 1,
    "جوان": 6,
    "جول": 7,
    "جولاءِ": 7,
    "جولائی": 7,
    "جولای": 7,
    "جون": 6,
    "جويلية": 7,
    "جەلتوقسان": 12,
    "حزيران": 6,
    "دجمبر": 12,
    "دجنبر": 12,
    "دسامبر": 12,
    "دسم": 12,
    "دسمبر": 12,
    "ديسمبر": 12,
    "سبتمبر": 9,
    "ستمبر": 9,
    "سيپٽمبر": 9,
    "سپتامبر": 9,
    "سپتمبر": 9,
    "سېپتمبر": 9,
    "شباط": 2,
    "شتمبر": 9,
    "شتنبر": 9,
    "شىلدە": 7,
    "غشت": 8,
    "فبراير": 2,
    "فبروري": 2,
    "فبروری": 2,
    "فروری": 2,
    "فوریه": 2,
    "فوریهٔ": 2,
    "فيبروري": 2,
    "فيفري": 2,
    "فېبروري": 2,
    "قاراشا": 11,
    "قازان": 10,
    "قاڭتار": 1,
    "قىركۇيەك": 9,
    "كانون الأول": 12,
    "كانون الثاني": 1,
    "مئي": 5,
    "مئی": 5,
    "مارس": 3,
    "مارچ": 3,
    "مامىر": 5,
    "ماي": 5,
    "مايو": 5,
    "ماۋسىم": 6,
    "مه": 5,
    "مهٔ": 5,
    "می": 5,
    "مۍ": 5,
    "ناۋرىز": 3,
    "نوامبر": 11,
    "نوفمبر": 11,
    "نومبر": 11,
    "نونبر": 11,
    "نيسان": 4,
    "يناير": 1,
    "يوليو": 7,
    "يوليوز": 7,
    "يونيو": 6,
    "ڊسمبر": 12,
    "ژانویه": 1,
    "ژانویهٔ": 1,
    "ژوئن": 6,
    "ژوئیه": 7,
    "ژوئیهٔ": 7,
    "अक्टूबर": 10,
    "अक्टू॰": 10,
    "अक्टोबर": 10,
    "अगस्ट": 8,
    "अगस्त": 8,
    "अग॰": 8,
    "अप्रिल": 4,
    "अप्रैल": 4,
    "एप्रि": 4,
    "एप्रिल": 4,
    "एप्री": 4,
    "एप्रील": 4,
    "ऑक्टो": 10,
    "ऑक्टोबर": 10,
    "ऑग": 8,
    "ऑगस्ट": 8,
    "जनवरी": 1,
    "जन॰": 1,
    "जाने": 1,
    "जानेवारी": 1,
    "जुन": 6,
    "जुल": 7,
    "जुलय": 7,
    "जुलाई": 7,
    "जुलै": 7,
    "जुल॰": 7,
    "जून": 6,
    "डिसे": 12,
    "डिसें": 12,
    "डिसेंबर": 12,
    "डिसेम्बर": 12,
    "दिसंबर": 12,
    "दिस॰": 12,
    "नवंबर": 11,
    "नव॰": 11,
    "नोभेम्बर": 11,
    "नोव्हें": 11,
    "नोव्हेंबर": 11,
    "फ़रवरी": 2,
    "फ़र॰": 2,
    "फेब्रु": 2,
    "फेब्रुअरी": 2,
    "फेब्रुवारी": 2,
    "मई": 5,
    "मार्च": 3,
    "मे": 5,
    "सप्टें": 9,
    "सप्टेंबर": 9,
    "सितंबर": 9,
    "सित॰": 9,
    "सेप्टेम्बर": 9,
    "অক্টো": 10,
    "অক্টোঃ": 10,
    "অক্টোবর": 10,
    "অক্টোবৰ": 10,
    "আগ": 8,
    "আগষ্ট": 8,
    "আগস্ট": 8,
    "এপ্রি": 4,
    "এপ্রিল": 4,
    "এপ্ৰিল": 4,
    "ছেপ্তে": 9,
    "ছেপ্তেম্বৰ": 9,
    "জানু": 1,
    "জানুয়ারি": 1,
    "জানুৱাৰী": 1,
    "জুন": 6,
    "জুল": 7,
    "জুলাই": 7,
    "ডিচে": 12,
    "ডিচেম্বৰ": 12,
    "ডিসে": 12,
    "ডিসেঃ": 12,
    "ডিসেম্বর": 12,
    "নভে": 11,
    "নভেঃ": 11,
    "নভেম্বর": 11,
    "নৱে": 11,
    "নৱেম্বৰ": 11,
    "ফেব": 2,
    "ফেব্রুয়ারি": 2,
    "ফেব্ৰু": 2,
    "ফেব্ৰুৱাৰী": 2,
    "মার্চ": 3,
    "মাৰ্চ": 3,
    "মে": 5,
    "মে’": 5,
    "সেপ": 9,
    "সেপ্ট": 9,
    "সেপ্টেঃ": 9,
    "সেপ্টেম্বর": 9,
    "ਅਕਤੂ": 10,
    "ਅਕਤੂਬਰ": 10,
    "ਅਗ": 8,
    "ਅਗਸਤ": 8,
    "ਅਪ੍ਰੈ": 4,
    "ਅਪ੍ਰੈਲ": 4,
    "ਜਨ": 1,
    "ਜਨਵਰੀ": 1,
    "ਜੁਲਾ": 7,
    "ਜੁਲਾਈ": 7,
    "ਜੂਨ": 6,
    "ਦਸੰ": 12,
    "ਦਸੰਬਰ": 12,
    "ਨਵੰ": 11,
    "ਨਵੰਬਰ": 11,
    "ਫ਼ਰ": 2,
    "ਫ਼ਰਵਰੀ": 2,
    "ਮਈ": 5,
    "ਮਾਰਚ": 3,
    "ਸਤੰ": 9,
    "ਸਤੰਬਰ": 9,
    "એપ્રિલ": 4,
    "ઑક્ટો": 10,
    "ઑક્ટોબર": 10,
    "ઑગસ્ટ": 8,
    "જાન્યુ": 1,
    "જાન્યુઆરી": 1,
    "જુલાઈ": 7,
    "જૂન": 6,
    "ડિસે": 12,
    "ડિસેમ્બર": 12,
    "નવે": 11,
    "નવેમ્બર": 11,
    "ફેબ્રુ": 2,
    "ફેબ્રુઆરી": 2,
    "માર્ચ": 3,
    "મે": 5,
    "સપ્ટે": 9,
    "સપ્ટેમ્બર": 9,
    "ଅକ୍ଟୋବର": 10,
    "ଅଗଷ୍ଟ": 8,
    "ଅପ୍ରେଲ": 4,
    "ଜାନୁଆରୀ": 1,
    "ଜୁନ": 6,
    "ଜୁଲାଇ": 7,
    "ଡିସେମ୍ବର": 12,
    "ନଭେମ୍ବର": 11,
    "ଫେବୃଆରୀ": 2,
    "ମଇ": 5,
    "ମାର୍ଚ୍ଚ": 3,
    "ସେପ୍ଟେମ୍ବର": 9,
    "அக்": 10,
    "அக்டோபர்": 10,
    "ஆக": 8,
    "ஆகஸ்ட்": 8,
    "ஏப்": 4,
    "ஏப்ரல்": 4,
    "செப்": 9,
    "செப்டம்பர்": 9,
    "ஜன": 1,
    "ஜனவரி": 1,
    "ஜூன்": 6,
    "ஜூலை": 7,
    "டிச": 12,
    "டிசம்பர்": 12,
    "நவ": 11,
    "நவம்பர்": 11,
    "பிப்": 2,
    "பிப்ரவரி": 2,
    "மார்": 3,
    "மார்ச்": 3,
    "மே": 5,
    "అక్టో": 10,
    "అక్టోబర్": 10,
    "ఆగ": 8,
    "ఆగస్టు": 8,
    "ఏప్రి": 4,
    "ఏప్రిల్": 4,
    "జన": 1,
    "జనవరి": 1,
    "జులై": 7,
    "జూన్": 6,
    "డిసెం": 12,
    "డిసెంబర్": 12,
    "నవం": 11,
    "నవంబర్": 11,
    "ఫిబ్ర": 2,
    "ఫిబ్రవరి": 2,
    "మార్చి": 3,
    "మే": 5,
    "సెప్టెం": 9,
    "సెప్టెంబర్": 9,
    "ಅಕ್ಟೋ": 10,
    "ಅಕ್ಟೋಬರ್": 10,
    "ಆಗ": 8,
    "ಆಗಸ್ಟ್": 8,
    "ಏಪ್ರಿ": 4,
    "ಏಪ್ರಿಲ್": 4,
    "ಜನ": 1,
    "ಜನವರಿ": 1,
    "ಜುಲೈ": 7,
    "ಜೂನ್": 6,
    "ಡಿಸೆಂ": 12,
    "ಡಿಸೆಂಬರ್": 12,
    "ನವೆಂ": 11,
    "ನವೆಂಬರ್": 11,
    "ಫೆಬ್ರ": 2,
    "ಫೆಬ್ರವರಿ": 2,
    "ಮಾರ್ಚ್": 3,
    "ಮೇ": 5,
    "ಸೆಪ್ಟೆಂ": 9,
    "ಸೆಪ್ಟೆಂಬರ್": 9,
    "ഏപ്രി": 4,
    "ഏപ്രിൽ": 4,
    "ഒക്ടോ": 10,
    "ഒക്‌ടോബർ": 10,
    "ഓഗ": 8,
    "ഓഗസ്റ്റ്": 8,
    "ജനു": 1,
    "ജനുവരി": 1,
    "ജൂലൈ": 7,
    "ജൂൺ": 6,
    "ഡിസം": 12,
    "ഡിസംബർ": 12,
    "നവം": 11,
    "നവംബർ": 11,
    "ഫെബ്രു": 2,
    "ഫെബ്രുവരി": 2,
    "മാർ": 3,
    "മാർച്ച്": 3,
    "മേയ്": 5,
    "സെപ്റ്റം": 9,
    "സെപ്റ്റംബർ": 9,
    "ඇසළ": 7,
    "ඉල්": 11,
    "උඳුවප්": 12,
    "දුරුතු": 1,
    "නවම්": 2,
    "නිකිණි": 8,
    "පොසොන්": 6,
    "බක්": 4,
    "බිනර": 9,
    "මැදින්": 3,
    "වප්": 10,
    "වෙසක්": 5,
    "ก.ค": 7,
    "ก.พ": 2,
    "ก.ย": 9,
    "กรกฎาคม": 7,
    "กันยายน": 9,
    "กุมภาพันธ์": 2,
    "ต.ค": 10,
    "ตุลาคม": 10,
    "ธ.ค": 12,
    "ธันวาคม": 12,
    "พ.ค": 5,
    "พ.ย": 11,
    "พฤศจิกายน": 11,
    "พฤษภาคม": 5,
    "ม.ค": 1,
    "มกราคม": 1,
    "มิ.ย": 6,
    "มิถุนายน": 6,
    "มี.ค": 3,
    "มีนาคม": 3,
    "ส.ค": 8,
    "สิงหาคม": 8,
    "เม.ย": 4,
    "เมษายน": 4,
    "ກ.ຍ": 9,
    "ກ.ພ": 2,
    "ກ.ລ": 7,
    "ກັນຍາ": 9,
    "ກຸມພາ": 2,
    "ກໍລະກົດ": 7,
    "ຕ.ລ": 10,
    "ຕຸລາ": 10,
    "ທ.ວ": 12,
    "ທັນວາ": 12,
    "ພ.ຈ": 11,
    "ພ.ພ": 5,
    "ພະຈິກ": 11,
    "ພຶດສະພາ": 5,
    "ມ.ກ": 1,
    "ມ.ນ": 3,
    "ມ.ສ": 4,
    "ມັງກອນ": 1,
    "ມິ.ຖ": 6,
    "ມິຖຸນາ": 6,
    "ມີນາ": 3,
    "ສ.ຫ": 8,
    "ສິງຫາ": 8,
    "ເມສາ": 4,
    "စက်": 9,
    "စက်တင်ဘာ": 9,
    "ဇန်": 1,
    "ဇန်နဝါရီ": 1,
    "ဇူ": 7,
    "ဇူလိုင်": 7,
    "ဇွန်": 6,
    "တီႇ": 12,
    "တီႇသႅမ်ႇပႃႇ": 12,
    "ဒီ": 12,
    "ဒီဇင်ဘာ": 12,
    "နို": 11,
    "နိုဝင်ဘာ": 11,
    "ဖေ": 2,
    "ဖေဖော်ဝါရီ": 2,
    "မတ်": 3,
    "မေ": 5,
    "မေႇ": 5,
    "မၢတ်ႉၶ်ျ": 3,
    "သႅပ်ႇ": 9,
    "သႅပ်ႇထႅမ်ႇပႃႇ": 9,
    "အောက်": 10,
    "အောက်တိုဘာ": 10,
    "ဢေႃး": 8,
    "ဢေႃးၵၢတ်ႉ": 8,
    "ဢေႇ": 4,
    "ဢေႇပရႄႇ": 4,
    "ဢွၵ်ႇ": 10,
    "ဢွၵ်ႇထူဝ်ႇပႃႇ": 10,
    "ဧ": 4,
    "ဧပြီ": 4,
    "ဩ": 8,
    "ဩဂုတ်": 8,
    "ၸုၼ်ႇ": 6,
    "ၸူႇ": 7,
    "ၸူႇလၢႆႇ": 7,
    "ၸၼ်ႇ": 1,
    "ၸၼ်ႇဝႃႇရီႇ": 1,
    "ၼူဝ်ႇ": 11,
    "ၼူဝ်ႇဝႅမ်ႇပႃႇ": 11,
    "ၾႅပ်ႇ": 2,
    "ၾႅပ်ႇဝႃႇရီႇ": 2,
    "აგვ": 8,
    "აგვისტო": 8,
    "აპრ": 4,
    "აპრილი": 4,
    "დეკ": 12,
    "დეკემბერი": 12,
    "თებ": 2,
    "თებერვალი": 2,
    "იან": 1,
    "იანვარი": 1,
    "ივლ": 7,
    "ივლისი": 7,
    "ივნ": 6,
    "ივნისი": 6,
    "მაი": 5,
    "მაისი": 5,
    "მარ": 3,
    "მარტი": 3,
    "ნოე": 11,
    "ნოემბერი": 11,
    "ოქტ": 10,
    "ოქტომბერი": 10,
    "სექ": 9,
    "სექტემბერი": 9,
    "ለካ": 2,
    "ለካቲት": 2,
    "ሓም": 7,
    "ሓምለ": 7,
    "ሕዳ": 11,
    "ሕዳር": 11,
    "መስ": 9,
    "መስከረም": 9,
    "መጋ": 3,
    "መጋቢት": 3,
    "ሚያ": 4,
    "ሚያዝያ": 4,
    "ማርች": 3,
    "ሜይ": 5,
    "ሰነ": 6,
    "ሴፕቴ": 9,
    "ሴፕቴምበር": 9,
    "ታሕ": 12,
    "ታሕሳስ": 12,
    "ነሓ": 8,
    "ነሓሰ": 8,
    "ኖቬም": 11,
    "ኖቬምበር": 11,
    "ኤፕሪ": 4,
    "ኤፕሪል": 4,
    "ኦክቶ": 10,
    "ኦክቶበር": 10,
    "ኦገስ": 8,
    "ኦገስት": 8,
    "ዲሴም": 12,
    "ዲሴምበር": 12,
    "ጁላይ": 7,
    "ጁን": 6,
    "ጃን": 1,
    "ጃንዋሪ": 1,
    "ጉንበት": 5,
    "ግን": 5,
    "ጥሪ": 1,
    "ጥቅ": 10,
    "ጥቅምቲ": 10,
    "ፌብ": 2,
    "ፌብሩዋሪ": 2,
    "ᎠᏂ": 5,
    "ᎠᏂᏍᎬᏘ": 5,
    "ᎠᏅ": 3,
    "ᎠᏅᏱ": 3,
    "ᎤᏃ": 1,
    "ᎤᏃᎸᏔᏅ": 1,
    "ᎥᏍ": 12,
    "ᎥᏍᎩᏱ": 12,
    "ᎦᎶ": 8,
    "ᎦᎶᏂ": 8,
    "ᎧᎦ": 2,
    "ᎧᎦᎵ": 2,
    "ᎧᏬ": 4,
    "ᎧᏬᏂ": 4,
    "ᎫᏰ": 7,
    "ᎫᏰᏉᏂ": 7,
    "ᏅᏓ": 11,
    "ᏅᏓᏕᏆ": 11,
    "ᏕᎭ": 6,
    "ᏕᎭᎷᏱ": 6,
    "ᏚᎵ": 9,
    "ᏚᎵᏍᏗ": 9,
    "ᏚᏂ": 10,
    "ᏚᏂᏅᏗ": 10,
    "កក្កដា": 7,
    "កញ្ញា": 9,
    "កុម្ភៈ": 2,
    "តុលា": 10,
    "ធ្នូ": 12,
    "មករា": 1,
    "មិថុនា": 6,
    "មីនា": 3,
    "មេសា": 4,
    "វិច្ឆិកា": 11,
    "សីហា": 8,
    "ឧសភា": 5,
    "ọgọ": 8,
    "ọgọst": 8,
    "ọgọọst": 8,
    "ọkt": 10,
    "ọktoba": 10,
    "ọktóba": 10,
    "ọ́gọ": 8,
    "ὀκτ": 10,
    "ὀκτωβρίου": 10,
    "ὀκτώβριοσ": 10,
    "一月": 1,
    "七月": 7,
    "三月": 3,
    "九月": 9,
    "二月": 2,
    "五月": 5,
    "八月": 8,
    "六月": 6,
    "十一月": 11,
    "十二月": 12,
    "十月": 10,
    "四月": 4,
}

WEEKDAYS: frozenset[str] = frozenset(
    {
        "ahad",
        "ahd",
        "ajé",
        "al",
        "alh",
        "alhamis",
        "alhamisi",
        "an",
        "ann",
        "anna",
        "antradienis",
        "aoine",
        "ar",
        "arbaco",
        "arbc",
        "asa",
        "asabar",
        "asteartea",
        "asteazkena",
        "astelehena",
        "axad",
        "axd",
        "az",
        "b",
        "b.e",
        "bazar",
        "bazar ertəsi",
        "ben",
        "benada",
        "bil",
        "biy",
        "biyernes",
        "budh",
        "budhwaar",
        "c",
        "c.a",
        "ceturtd",
        "ceturtdiena",
        "chor",
        "chorshanba",
        "chủ nhật",
        "cmt",
        "cn",
        "cs",
        "csütörtök",
        "cum",
        "cuma",
        "cumartesi",
        "czw",
        "czwartek",
        "céad",
        "cümə",
        "cümə axşamı",
        "dc",
        "dg",
        "di",
        "dia",
        "diardaoin",
        "diciadain",
        "did",
        "didòmhnaich",
        "die",
        "dienstag",
        "dih",
        "dihaoine",
        "dijous",
        "dil",
        "dilluns",
        "diluain",
        "dim",
        "dimanche",
        "dimarts",
        "dimecres",
        "dimàirt",
        "dinsdag",
        "disathairne",
        "dissabte",
        "diumenge",
        "divendres",
        "dj",
        "dl",
        "do",
        "dom",
        "domenica",
        "domh",
        "domingo",
        "donderdag",
        "donnerstag",
        "ds",
        "dt",
        "du",
        "dum",
        "dumengia",
        "duminică",
        "dush",
        "dushanba",
        "duş",
        "duşenbe",
        "dv",
        "dwo",
        "dwoada",
        "dydd gwener",
        "dydd iau",
        "dydd llun",
        "dydd mawrth",
        "dydd mercher",
        "dydd sadwrn",
        "dydd sul",
        "dé céadaoin",
        "dé domhnaigh",
        "dé haoine",
        "dé luain",
        "dé máirt",
        "dé sathairn",
        "déar",
        "déardaoin",
        "e",
        "e diel",
        "e enjte",
        "e hënë",
        "e martë",
        "e mërkurë",
        "e premte",
        "e shtunë",
        "enj",
        "esmaspäev",
        "fia",
        "fiada",
        "fim",
        "fimmtudagur",
        "fr",
        "fraí",
        "fraídè",
        "fraị",
        "fraịdee",
        "fre",
        "fredag",
        "freitag",
        "fri",
        "friday",
        "fös",
        "föstudagur",
        "gie",
        "gievgia",
        "gio",
        "giovedì",
        "gli",
        "glindesdi",
        "guru",
        "guruwaar",
        "gwe",
        "gwen",
        "h",
        "hla",
        "huw",
        "huwebes",
        "hétfő",
        "hën",
        "iau",
        "ig",
        "igandea",
        "ijumaa",
        "isn",
        "isniin",
        "isnin",
        "isonto",
        "jeu",
        "jeudi",
        "jimco",
        "jmc",
        "joi",
        "jue",
        "jueves",
        "jum",
        "juma",
        "jumaat",
        "jumamosi",
        "jumanne",
        "jumapili",
        "jumat",
        "jumatano",
        "jumatatu",
        "jummaʼa",
        "k",
        "kam",
        "kamis",
        "ke",
        "kedd",
        "keskiviikko",
        "keskiviikkona",
        "ketvirtadienis",
        "kha",
        "khamiis",
        "khamis",
        "khms",
        "kolmapäev",
        "kt",
        "kwa",
        "l",
        "la",
        "lah",
        "lahadi",
        "lar",
        "laraba",
        "larunbata",
        "lau",
        "lauantai",
        "lauantaina",
        "laugardagur",
        "laupäev",
        "laurdag",
        "lin",
        "linggo",
        "lit",
        "litinin",
        "llun",
        "lr",
        "luan",
        "lun",
        "lundi",
        "lunedì",
        "lunes",
        "luni",
        "luns",
        "lör",
        "lördag",
        "lør",
        "lørdag",
        "ma",
        "maanantai",
        "maanantaina",
        "maandag",
        "man",
        "mandag",
        "mangal",
        "mangalwaar",
        "mardi",
        "martedì",
        "martes",
        "marți",
        "me",
        "mem",
        "memeneda",
        "mer",
        "mercoledì",
        "mercredi",
        "mesemna",
        "mgq",
        "mi",
        "mie",
        "miercuri",
        "min",
        "minggu",
        "mittwoch",
        "miy",
        "miyerkules",
        "mié",
        "miércoles",
        "mið",
        "miðvikudagur",
        "mo",
        "mon",
        "monday",
        "montag",
        "mso",
        "máirt",
        "mán",
        "mánudagur",
        "må",
        "mån",
        "måndag",
        "mér",
        "mércores",
        "mër",
        "mọn",
        "mọnde",
        "mọ́n",
        "mọ́ndè",
        "n",
        "ne",
        "ned",
        "nedelja",
        "nedeľa",
        "nedjelja",
        "neděle",
        "neljapäev",
        "niedz",
        "niedziela",
        "nje",
        "njedźela",
        "njeźela",
        "og",
        "on",
        "ons",
        "onsdag",
        "or",
        "osteguna",
        "ostirala",
        "otrd",
        "otrdiena",
        "p",
        "pay",
        "payshanba",
        "paz",
        "pazar",
        "pazartesi",
        "pe",
        "pen",
        "penktadienis",
        "penşenbe",
        "per",
        "perjantai",
        "perjantaina",
        "perşembe",
        "pet",
        "petak",
        "petek",
        "pi",
        "piatok",
        "piektd",
        "piektdiena",
        "pirmadienis",
        "pirmd",
        "pirmdiena",
        "piątek",
        "pja",
        "pjatk",
        "pn",
        "po",
        "pon",
        "pondelok",
        "pondělí",
        "ponedeljak",
        "ponedeljek",
        "ponedjeljak",
        "poniedziałek",
        "pr",
        "pre",
        "pt",
        "pzt",
        "pá",
        "pátek",
        "péntek",
        "pón",
        "póndźela",
        "pónjeźele",
        "pühapäev",
        "pět",
        "pětk",
        "qua",
        "quarta",
        "quarta-feira",
        "qui",
        "quinta",
        "quinta-feira",
        "r",
        "rab",
        "rabu",
        "ravi",
        "raviwaar",
        "reede",
        "sa",
        "sab",
        "sabado",
        "sabato",
        "sabti",
        "sabtu",
        "sad",
        "sal",
        "salı",
        "sam",
        "samedi",
        "samstag",
        "saterdag",
        "sath",
        "saturday",
        "satọdee",
        "sbti",
        "seg",
        "segunda",
        "segunda-feira",
        "sekmadienis",
        "sel",
        "selasa",
        "senin",
        "sesh",
        "seshanba",
        "sestd",
        "sestdiena",
        "sex",
        "sexta",
        "sexta-feira",
        "shan",
        "shanba",
        "shani",
        "shaniwaar",
        "shukra",
        "shukrawaar",
        "sin",
        "siş",
        "sişenbe",
        "sk",
        "so",
        "sob",
        "sobota",
        "som",
        "somwaar",
        "son",
        "sonda",
        "sondag",
        "sonntag",
        "sre",
        "sreda",
        "sri",
        "srijeda",
        "srj",
        "srjeda",
        "srjoda",
        "st",
        "streda",
        "stw",
        "stwórtk",
        "středa",
        "su",
        "sub",
        "subota",
        "sul",
        "sun",
        "sunday",
        "sunnudagur",
        "sunnuntai",
        "sunnuntaina",
        "svētd",
        "svētdiena",
        "sze",
        "szerda",
        "szo",
        "szombat",
        "sáb",
        "sábado",
        "sát",
        "sátọdè",
        "sâm",
        "sâmbătă",
        "sön",
        "söndag",
        "sø",
        "søn",
        "søndag",
        "sọn",
        "sọndee",
        "sọ́n",
        "sọ́ndè",
        "t",
        "tal",
        "talaado",
        "talata",
        "teisipäev",
        "ter",
        "terça",
        "terça-feira",
        "tha",
        "thu",
        "thursday",
        "thứ ba",
        "thứ bảy",
        "thứ hai",
        "thứ năm",
        "thứ sáu",
        "thứ tư",
        "ti",
        "tiistai",
        "tiistaina",
        "tir",
        "tirs",
        "tirsdag",
        "tis",
        "tisdag",
        "tiu",
        "tiuzdee",
        "tiú",
        "tiúzdè",
        "tldo",
        "to",
        "tor",
        "torek",
        "tors",
        "torsdag",
        "torstai",
        "torstaina",
        "tr",
        "trečiadienis",
        "trešd",
        "trešdiena",
        "tue",
        "tuesday",
        "ty",
        "tys",
        "tysdag",
        "tọ́z",
        "tọ́zdè",
        "tọọ",
        "tọọzdee",
        "ulwesibili",
        "ulwesihlanu",
        "ulwesine",
        "ulwesithathu",
        "umgqibelo",
        "umsombuluko",
        "ut",
        "uto",
        "utorak",
        "utorok",
        "v",
        "vasárnap",
        "ve",
        "ven",
        "venderdi",
        "vendredi",
        "venerdì",
        "venres",
        "vie",
        "viernes",
        "vin",
        "vineri",
        "vr",
        "vrijdag",
        "vrydag",
        "wał",
        "wałtora",
        "wed",
        "wednesday",
        "wen",
        "wenezdee",
        "wo",
        "woensdag",
        "wt",
        "wtorek",
        "wuk",
        "wukuada",
        "wut",
        "wutora",
        "wẹ́n",
        "wẹ́nẹ́zdè",
        "xov",
        "xoves",
        "yak",
        "yakshanba",
        "yaw",
        "yawoada",
        "za",
        "zaterdag",
        "zo",
        "zondag",
        "àbámɛ́ta",
        "àbámẹ́ta",
        "àìkú",
        "ç",
        "ç.a",
        "çar",
        "çarşamba",
        "çarşenbe",
        "çərşənbə",
        "çərşənbə axşamı",
        "ìsɛ́gun",
        "ìsẹ́gun",
        "út",
        "úterý",
        "ýek",
        "ýekşenbe",
        "þri",
        "þriðjudagur",
        "čet",
        "četrtek",
        "četvrtak",
        "čt",
        "čtvrtek",
        "śr",
        "środa",
        "ş",
        "şen",
        "şenbe",
        "şənbə",
        "šeštadienis",
        "št",
        "štvrtok",
        "štw",
        "štwórtk",
        "ɔjɔ́ ajé",
        "ɔjɔ́ àbámɛ́ta",
        "ɔjɔ́ àìkú",
        "ɔjɔ́ ìsɛ́gun",
        "ɔjɔ́ ɛtì",
        "ɔjɔ́bɔ",
        "ɔjɔ́rú",
        "ɛtì",
        "δευ",
        "δευτέρα",
        "κυρ",
        "κυριακή",
        "πέμ",
        "πέμπτη",
        "παρ",
        "παρασκευή",
        "σάβ",
        "σάββατο",
        "τετ",
        "τετάρτη",
        "τρί",
        "τρίτη",
        "аў",
        "аўторак",
        "ба",
        "баасан",
        "бейсенбі",
        "бейш",
        "бейшемби",
        "бс",
        "бя",
        "бямба",
        "воскресенье",
        "вр",
        "вс",
        "вт",
        "вто",
        "вторник",
        "вырсарни кун",
        "вівторок",
        "да",
        "даваа",
        "дс",
        "дүй",
        "дүйсенбі",
        "дүйшөмбү",
        "дүш",
        "дүшәмбе",
        "жек",
        "жексенбі",
        "жекшемби",
        "жм",
        "жс",
        "жума",
        "жұма",
        "ишемби",
        "ишм",
        "йом",
        "йома",
        "йәк",
        "йәкшәмбе",
        "кес",
        "кесаҙна",
        "кҫ",
        "кӗҫнерни кун",
        "лх",
        "лхагва",
        "мя",
        "мягмар",
        "нд",
        "нед",
        "недела",
        "неделя",
        "недеља",
        "неділя",
        "недјеља",
        "ня",
        "нядзеля",
        "ням",
        "пʼятниця",
        "панядзелак",
        "пет",
        "петак",
        "петок",
        "петък",
        "пн",
        "пон",
        "понеделник",
        "понедельник",
        "понедељак",
        "понеділок",
        "понедјељак",
        "пт",
        "пятница",
        "пятніца",
        "пү",
        "пүрэв",
        "саб",
        "сабота",
        "сб",
        "сейсенбі",
        "сенбі",
        "серада",
        "середа",
        "ср",
        "сре",
        "среда",
        "сри",
        "сриједа",
        "сряда",
        "сс",
        "суб",
        "суббота",
        "субота",
        "събота",
        "сәрсенбі",
        "тн",
        "тунти кун",
        "уто",
        "уторак",
        "чацвер",
        "чет",
        "четвер",
        "четверг",
        "четвртак",
        "четврток",
        "четвъртък",
        "чт",
        "чц",
        "шар",
        "шарш",
        "шаршамбы",
        "шаршемби",
        "шейш",
        "шейшемби",
        "шиш",
        "шишәмбе",
        "шм",
        "шӑмат кун",
        "шәм",
        "шәмбе",
        "ыт",
        "ытлари кун",
        "эр",
        "эрне кун",
        "юн",
        "юн кун",
        "երեքշաբթի",
        "երկ",
        "երկուշաբթի",
        "երք",
        "կիր",
        "կիրակի",
        "հինգշաբթի",
        "հնգ",
        "շաբաթ",
        "շբթ",
        "ուր",
        "ուրբաթ",
        "չորեքշաբթի",
        "չրք",
        "יום א׳",
        "יום ב׳",
        "יום ג׳",
        "יום ד׳",
        "יום ה׳",
        "יום ו׳",
        "יום חמישי",
        "יום ראשון",
        "יום רביעי",
        "יום שבת",
        "יום שישי",
        "יום שלישי",
        "יום שני",
        "שבת",
        "آچر",
        "اتوار",
        "اربع",
        "الأحد",
        "الأربعاء",
        "الاثنين",
        "الثلاثاء",
        "الجمعة",
        "الخميس",
        "السبت",
        "اونۍ",
        "اڱارو",
        "بدھ",
        "بەي",
        "بەيسەنبى",
        "جمعرات",
        "جمعه",
        "جمعو",
        "جمعہ",
        "جۇم",
        "جۇما",
        "جەك",
        "جەكسەنبى",
        "خميس",
        "درېنۍ",
        "دوشنبه",
        "دونۍ",
        "دۇي",
        "دۇيسەنبى",
        "سار",
        "سارسەنبى",
        "سه‌شنبه",
        "سومر",
        "سەن",
        "سەنبى",
        "سەي",
        "سەيسەنبى",
        "شنبه",
        "منگل",
        "يونۍ",
        "پنجشنبه",
        "پينځنۍ",
        "پیر",
        "څلرنۍ",
        "چهارشنبه",
        "ڇنڇر",
        "ہفتہ",
        "یکشنبه",
        "आइत",
        "आइतबार",
        "आयतार",
        "गुरु",
        "गुरुवार",
        "बिरेस्तार",
        "बिहि",
        "बिहिबार",
        "बुध",
        "बुधबार",
        "बुधवार",
        "मंगल",
        "मंगलवार",
        "मंगळ",
        "मंगळवार",
        "मंगळार",
        "मङ्गल",
        "मङ्गलबार",
        "रवि",
        "रविवार",
        "शनि",
        "शनिबार",
        "शनिवार",
        "शुक्र",
        "शुक्रबार",
        "शुक्रवार",
        "शुक्रार",
        "शेनवार",
        "सोम",
        "सोमबार",
        "सोमवार",
        "सोमार",
        "দেও",
        "দেওবাৰ",
        "বুধ",
        "বুধবার",
        "বুধবাৰ",
        "বৃহ",
        "বৃহস্পতি",
        "বৃহস্পতিবার",
        "বৃহস্পতিবাৰ",
        "মঙ্গল",
        "মঙ্গলবার",
        "মঙ্গলবাৰ",
        "রবি",
        "রবিবার",
        "শনি",
        "শনিবার",
        "শনিবাৰ",
        "শুক্র",
        "শুক্রবার",
        "শুক্ৰ",
        "শুক্ৰবাৰ",
        "সোম",
        "সোমবার",
        "সোমবাৰ",
        "ਐਤ",
        "ਐਤਵਾਰ",
        "ਬੁੱਧ",
        "ਬੁੱਧਵਾਰ",
        "ਮੰਗਲ",
        "ਮੰਗਲਵਾਰ",
        "ਵੀਰ",
        "ਵੀਰਵਾਰ",
        "ਸ਼ਨੀ",
        "ਸ਼ਨੀਵਾਰ",
        "ਸ਼ੁੱਕਰ",
        "ਸ਼ੁੱਕਰਵਾਰ",
        "ਸੋਮ",
        "ਸੋਮਵਾਰ",
        "ગુરુ",
        "ગુરુવાર",
        "બુધ",
        "બુધવાર",
        "મંગળ",
        "મંગળવાર",
        "રવિ",
        "રવિવાર",
        "શનિ",
        "શનિવાર",
        "શુક્ર",
        "શુક્રવાર",
        "સોમ",
        "સોમવાર",
        "ଗୁରୁ",
        "ଗୁରୁବାର",
        "ବୁଧ",
        "ବୁଧବାର",
        "ମଙ୍ଗଳ",
        "ମଙ୍ଗଳବାର",
        "ରବି",
        "ରବିବାର",
        "ଶନି",
        "ଶନିବାର",
        "ଶୁକ୍ର",
        "ଶୁକ୍ରବାର",
        "ସୋମ",
        "ସୋମବାର",
        "சனி",
        "செவ்",
        "செவ்வாய்",
        "ஞாயி",
        "ஞாயிறு",
        "திங்",
        "திங்கள்",
        "புத",
        "புதன்",
        "வியா",
        "வியாழன்",
        "வெள்",
        "வெள்ளி",
        "ఆది",
        "ఆదివారం",
        "గురు",
        "గురువారం",
        "బుధ",
        "బుధవారం",
        "మంగళ",
        "మంగళవారం",
        "శని",
        "శనివారం",
        "శుక్ర",
        "శుక్రవారం",
        "సోమ",
        "సోమవారం",
        "ಗುರು",
        "ಗುರುವಾರ",
        "ಬುಧ",
        "ಬುಧವಾರ",
        "ಭಾನು",
        "ಭಾನುವಾರ",
        "ಮಂಗಳ",
        "ಮಂಗಳವಾರ",
        "ಶನಿ",
        "ಶನಿವಾರ",
        "ಶುಕ್ರ",
        "ಶುಕ್ರವಾರ",
        "ಸೋಮ",
        "ಸೋಮವಾರ",
        "ചൊവ്വ",
        "ചൊവ്വാഴ്ച",
        "ചൊവ്വാഴ്‌ച",
        "ഞായറാഴ്‌ച",
        "ഞായർ",
        "തിങ്കളാഴ്‌ച",
        "തിങ്കൾ",
        "ബുധനാഴ്‌ച",
        "ബുധൻ",
        "വെള്ളി",
        "വെള്ളിയാഴ്‌ച",
        "വ്യാഴം",
        "വ്യാഴാഴ്‌ച",
        "ശനി",
        "ശനിയാഴ്‌ച",
        "අඟහ",
        "අඟහරුවාදා",
        "ඉරිදා",
        "බදාදා",
        "බ්‍රහස්",
        "බ්‍රහස්පතින්දා",
        "සඳුදා",
        "සිකු",
        "සිකුරාදා",
        "සෙන",
        "සෙනසුරාදා",
        "จันทร์",
        "พฤหัส",
        "พุธ",
        "วันจันทร์",
        "วันพฤหัสบดี",
        "วันพุธ",
        "วันศุกร์",
        "วันอังคาร",
        "วันอาทิตย์",
        "วันเสาร์",
        "ศุกร์",
        "อังคาร",
        "อาทิตย์",
        "เสาร์",
        "ຈັນ",
        "ພະຫັດ",
        "ພຸດ",
        "ວັນຈັນ",
        "ວັນພະຫັດ",
        "ວັນພຸດ",
        "ວັນສຸກ",
        "ວັນອັງຄານ",
        "ວັນອາທິດ",
        "ວັນເສົາ",
        "ສຸກ",
        "ອັງຄານ",
        "ອາທິດ",
        "ເສົາ",
        "ကြာသပတေး",
        "စနေ",
        "တနင်္ဂနွေ",
        "တနင်္လာ",
        "တိတ်ႉ",
        "ပုတ်ႉ",
        "ဗုဒ္ဓဟူး",
        "ဝၼ်းပုတ်ႉ",
        "ဝၼ်းသဝ်",
        "ဝၼ်းသုၵ်း",
        "ဝၼ်းဢင်းၵၢၼ်း",
        "ဝၼ်းဢႃးတိတ်ႉ",
        "ဝၼ်းၸၼ်",
        "ဝၼ်းၽတ်း",
        "သဝ်",
        "သုၵ်း",
        "သောကြာ",
        "အင်္ဂါ",
        "ၵၢၼ်း",
        "ၸၼ်",
        "ၽတ်း",
        "კვი",
        "კვირა",
        "ოთხ",
        "ოთხშაბათი",
        "ორშ",
        "ორშაბათი",
        "პარ",
        "პარასკევი",
        "სამ",
        "სამშაბათი",
        "შაბ",
        "შაბათი",
        "ხუთ",
        "ხუთშაბათი",
        "ሐሙስ",
        "ሓሙ",
        "ሓሙስ",
        "ማክሰ",
        "ማክሰኞ",
        "ረቡ",
        "ረቡዕ",
        "ሰሉ",
        "ሰሉስ",
        "ሰኑ",
        "ሰኑይ",
        "ሰን",
        "ሰንበት",
        "ሰኞ",
        "ቀዳ",
        "ቀዳም",
        "ቅዳሜ",
        "እሑድ",
        "ዓር",
        "ዓርቢ",
        "ዓርብ",
        "ᎤᎾᏙᏓᏆᏍᎬ",
        "ᎤᎾᏙᏓᏈᏕᎾ",
        "ᎤᎾᏙᏓᏉᏅᎯ",
        "ᏅᎩᏁ",
        "ᏅᎩᏁᎢᎦ",
        "ᏆᏍᎬ",
        "ᏈᏕᎾ",
        "ᏉᏅᎯ",
        "ᏔᎵᏁ",
        "ᏔᎵᏁᎢᎦ",
        "ᏦᎢᏁ",
        "ᏦᎢᏁᎢᎦ",
        "ᏧᎾᎩ",
        "ᏧᎾᎩᎶᏍᏗ",
        "ចន្ទ",
        "ច័ន្ទ",
        "ពុធ",
        "ព្រហ",
        "ព្រហស្បតិ៍",
        "សុក្រ",
        "សៅរ៍",
        "អង្គារ",
        "អាទិត្យ",
        "ẹtì",
        "ọjọ́ ajé",
        "ọjọ́ àbámẹ́ta",
        "ọjọ́ àìkú",
        "ọjọ́ ìsẹ́gun",
        "ọjọ́ ẹtì",
        "ọjọ́bọ",
        "ọjọ́rú",
        "周一",
        "周三",
        "周二",
        "周五",
        "周六",
        "周四",
        "周日",
        "土",
        "土曜日",
        "日",
        "日曜日",
        "星期一",
        "星期三",
        "星期二",
        "星期五",
        "星期六",
        "星期四",
        "星期日",
        "月",
        "月曜日",
        "木",
        "木曜日",
        "水",
        "水曜日",
        "火",
        "火曜日",
        "週一",
        "週三",
        "週二",
        "週五",
        "週六",
        "週四",
        "週日",
        "金",
        "金曜日",
        "금",
        "금요일",
        "목",
        "목요일",
        "수",
        "수요일",
        "월",
        "월요일",
        "일",
        "일요일",
        "토",
        "토요일",
        "화",
        "화요일",
    }
)
